var cbx={ver:820,lp:0,prefs:{sndVol:100,timeDelta:0},user:{key:null,lvl:null,nme:null,eml:null,lpid:null}};window.tbl=null;window.cbm=null;if(document.currentScript){var matches=document.currentScript.src.match(/_(.*)\.js/);matches&&1<matches.length&&(cbx.build=matches[1])}
window.c2init=function(){cbx.debug.log("init: starting");var a=document.forms.cbox;window.f=cbx.$frm=a;var b=cbx.store.restore(s_id+":user",cbx.user),c=getcookie("key_"+s_id);null==c||cbx.user.key||cbx.updateKey(c);s_uo?(cbx.updateKey(a.key.value),cbx.user.nme=a.nme.value):(cbx.user.key&&cbx.updateKey(cbx.user.key),cbx.user.nme&&(a.nme.value=cbx.user.nme),a.eml&&cbx.user.eml&&(a.eml.value=cbx.user.eml));!s_uo||""!=a.nme.value&&""!=a.key.value||(a.pst.value=t0);var d=cbx.store.restore("_:prefs",cbx.prefs);
window.onbeforeunload=function(){cbx.store.save("_:prefs",cbx.prefs,d);cbx.store.save(s_id+":user",cbx.user,b)};window.onfocus=function(){cbx.notifyParent("gotFormFocus",null)};window.onblur=function(){cbx.notifyParent("lostFormFocus",null)};s_sn&&window.setTimeout(function(){cbx.setSndVol(cbx.prefs.sndVol);cbx.audio.setup(sndpath+["blip1","click","blip2"][s_sn-1])},1500);window.setTimeout(function(){cbx.rsz()},10);document.body.onresize=cbx.rsz;document.body.onselectstart=function(a){a=(a=a||window.event)&&
a.srcElement?a.srcElement.tagName.toLowerCase():"";return"textarea"!=a&&"input"!=a?!1:!0};try{(cbm=parent["cboxmain"+s_no])&&cbm.ready&&window.cbmready(cbm,!0)}catch(e){}};
window.cbmready=function(a,b){cbx.debug.log("cbmready called "+(b?"locally":"remotely")+": importing");var c=cbx.$frm;c?(window.cbm=a,window.tbl=a.document.getElementById("mt").tBodies[0],!a.frld&&1*window.ctme+5<1*a.ftme&&(a.frld=!0,window.setTimeout(function(){document.location.reload(!0)},1E3)),cbx.lp=Math.max(cbx.lp,1*a.lpid),s_on&&a.onu&&cbx.aonliners(1*a.onu),a.exp&&(c.pst.value=a.exp,c.pst.disabled="true",c.sub.disabled="true"),a.nme&&c.nme.value==t1&&(cbx.user.nme=a.nme,c.nme.value=a.nme),
a.eml&&c.eml&&c.eml.value==t5&&(cbx.user.eml=a.eml,c.eml.value=a.eml),cbm.onscroll=cbx.onScroll,cbx.disableAutoScroll=!1,window.setInterval(cbx.autoScroll,500),cbm.onresize=function(){cbx.autoScroll()},cbx.delban(),cbx.upd_tms(),ar_reset(),a.onunload=function(){a=cbx.$body=null}):cbx.debug.log("cbmready race detected. Bailing.")};"undefined"===typeof JSON&&(window.JSON={parse:function(){},stringify:function(){}});
cbx.store={set:function(a,b,c){localStorage&&(b={ctime:(new Date).getTime()/1E3|0,val:b},c&&(b.ttl=1*c),localStorage.setItem("cbx:"+a,JSON.stringify(b)))},get:function(a){if(localStorage&&(a=localStorage.getItem("cbx:"+a),null!==a)){try{var b=JSON.parse(a)}catch(c){return}return b&&b.val?b.val:b}},restore:function(a,b){var c=cbx.store.get(a)||{},d={},e;for(e in b)"undefined"!==typeof c[e]&&(b[e]=c[e]),d[e]=b[e];return d},save:function(a,b,c){var d=!1,e=cbx.store.get(a)||{},g;for(g in c)c[g]!==b[g]&&
(e[g]=b[g],d=!0);d&&cbx.store.set(a,e)}};function getcookie(a){var b=document.cookie,c=b.indexOf(a+"=",0);if(-1<c){var d=b.indexOf(";",c),d=-1==d?b.length:d;return b.substring(c+a.length+1,d)}return null}cbx.printDebug=function(){set_status("V: "+js_ok)};cbx.notifyParent=function(a,b){if(!window.postMessage)return!1;window.parent.postMessage(a,"*")};
cbx.debug={history:[],log:function(a){var b=cbx.debug;b.history.push(((new Date).getTime()/1E3).toFixed(3)+" "+a);50<b.history.length&&b.history.shift()},stringify:function(a){if("string"===typeof a||"number"===typeof a)return a;var b=[],c;for(c in a)b.push(c+": "+a[c]);return b.join(", ")}};
window.performance&&window.performance.webkitSetResourceTimingBufferSize&&(window.performance.onwebkitresourcetimingbufferfull=function(a){a=window.performance.getEntries();a=a[a.length-1];var b=[],c=Math.round(window.performance.now()),d=[],e;for(e in a)b[e]="number"===typeof a[e]?Math.round(a[e]):a[e],d.push(e+"="+b[e]);cbx.debug.log("PERF (NOW = "+c+"): "+d.join(","));window.performance.webkitClearResourceTimings()},window.performance.webkitClearResourceTimings(),window.performance.webkitSetResourceTimingBufferSize(1));
cbx.debugOverlay={ovr:null,updTmr:null,visible:!1,update:function(){var a=cbx.debugOverlay.ovr,b=[];b.push("<b>Version:</b>  "+cbx.ver+" build "+cbx.build+" in "+document.compatMode+"<br>");b.push("<b>Namespace:</b>  "+s_phost+"-"+s_id+"-"+s_tid+" ("+s_no+")<br>");b.push("<b>User Agent:</b> "+navigator.userAgent+"<br>");b.push("<b>Time:</b> "+(new Date).getTime()+", scomp: "+cbx.unixTime()+"<br>");b.push("<b>Prefs:</b> "+cbx.debug.stringify(cbx.prefs)+"<br>");b.push("<b>User:</b> "+cbx.debug.stringify(cbx.user)+
"<br>");b.push("<b>LP ID:</b> "+cbx.lp+"<br>");b.push("<b>Scroll lock:</b> "+scrollFollow+"<br>");b.push("<b>ARMGR state:</b> "+cbx.arMgr.state+", wait: "+cbx.arMgr.backoff+"<br>");b.push("<b>WS/FL state:</b> "+wsconn.state+" / "+flconn.state+"<br>");b.push("<b>LP state:</b> "+cbx.debug.stringify(cbx.lpconn)+"<br>");b.push("<b>Log</b><br>");for(var c in cbx.debug.history)b.push(cbx.debug.history[c]+"<br>");a.innerHTML=b.join("")},show:function(){if(cbm){var a=this.ovr;null===a&&(a=cbm.document.createElement("div"),
a.style.position="fixed",s_sd?a.style.top="0":a.style.bottom="0",a.style.left="0",a.style.right="0",a.style.height="50%",a.style.overflow="auto",a.style.color="#fff",a.style.fontSize="12px",a.style.fontFamily="monospace",a.style.wordWrap="break-word",a.style.background="rgb(0, 0, 0)",a.style.opacity="0.8",a.style.padding="6px",this.ovr=a);cbm.document.getElementById("bdy").appendChild(this.ovr);this.visible=!0}},hide:function(){if(!this.ovr||!this.visible)return!1;cbm.document.getElementById("bdy").removeChild(this.ovr);
this.updTmr&&window.clearInterval(this.updTmr);this.updTmr=null;this.visible=!1},toggle:function(){this.visible?this.hide():(this.show(),this.update())},autorefresh:function(){this.hide();this.show();this.updTmr=window.setInterval(this.update,300);this.update()}};cbx.cmdHistory=cbx.store.get("cmdHistory")||[];cbx.cmdCursor=0;
cbx.cmdExec=function(a){if("//"!==a.substring(0,2))return!1;var b=cbx.$frm;b.pst.onkeydown=function(a){a=a||window.event;"INPUT"===b.pst.tagName&&(38==a.keyCode&&cbx.cmdCursor+1<cbx.cmdHistory.length&&(cbx.cmdHistory[cbx.cmdCursor]=b.pst.value,b.pst.value=cbx.cmdHistory[++cbx.cmdCursor],a.preventDefault()),40==a.keyCode&&cbx.cmdHistory.length&&cbx.cmdCursor&&(cbx.cmdHistory[cbx.cmdCursor]=b.pst.value,b.pst.value=cbx.cmdHistory[--cbx.cmdCursor],a.preventDefault()))};a!==cbx.cmdHistory[0]&&(cbx.cmdHistory[0]=
a,cbx.cmdHistory.unshift(""),10<cbx.cmdHistory.length&&cbx.cmdHistory.pop());cbx.cmdCursor=0;a=a.substring(2).split(" ");switch(a[0]){case "debug":switch(a[1]){case "watch":cbx.debugOverlay.autorefresh();break;default:cbx.debugOverlay.toggle()}break;case "reload":switch(a[1]){case "all":cbm.location.reload(!0);default:window.location.reload(!0)}break;case "ping":cbx.doPing();break;case "login":case "profile":p_open();break;case "smilies":pop("smilies",640,400,1);break;case "captcha":cbx.doCaptcha();
break;case "scroll":switch(a[1]){default:cbx.disableAutoScroll=!cbx.disableAutoScroll}break;case "ignore":break;case "tetris":var c=window.open("","","width=300, height=400, resizable=yes");c.document.write('<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body id="bdy" style="position:absolute;margin:0;width:100%;height:100%;"></body></html>');c.document.close();c.document.title="TETRIS!";var d=c.document.getElementById("bdy");c.onTetrisReady=
function(a){a=new a(d);c.onresize=a.redraw;c.onblur=a.pause;c.onfocus=a.resume;a.start()};a=c.document.createElement("script");a.src="//static.cbox.ws/jsc/tetris.js?1";d.appendChild(a);break;default:set_status("Unknown command <b>"+a[0]+"</b>.")}return!0};
cbx.rpcProcess=function(a,b){var c=[];"<"==a.substring(0,1)&&(c=a.substring(1).split("="));if(0<c.length)switch(c[0]){case "del":cbx.proc_rpc_del(c[1]);break;case "updusrcnt":cbx.aonliners(c[1]);break;case "ping":c[1]&&add_peer_post("Ping reply (WS): "+Math.round((new Date).getTime()-1*c[1])+" ms");break;default:b(c[0],c[1])}else cbx.parseMsg(a),cbx.delban(),cbx.upd_tms()};
cbx.doPing=function(){var a=(new Date).getTime(),b="";4===wsconn.state&&(b="&ping="+a+"&cid="+wsconn.id+"&chash="+wsconn.hash);cbx.xhr("./?"+s_rq+"&sec=ar"+b,null,function(b,d){if(!b||d)"L-timeout"==d?set_status("Ping timeout"):set_status(d);else{var e=(new Date).getTime()-a;add_peer_post("Ping reply (XHR): "+Math.round(e)+" ms")}},5E3)};var relax=!1;
window.do_refresh=function(){if(null==tbl)return!0;set_status(t9);cbx.autoScroll(!0);if(relax)return window.setTimeout("set_status(t10)",500),!1;relax=!0;window.setTimeout(function(){relax=!1},1E4);cbx.xhr("./?"+s_rq+"&sec=ar&p="+cbx.lp+"&c="+cbx.unixTime(),null,function(a,b){!a||b?set_status(b):cbx.aj_proc(a)||set_status(t10)});return!1};
window.do_post=function(){var a=cbx.$frm,b=a.pst.value;if(null==tbl)return!0;if(cbx.cmdExec&&cbx.cmdExec(b))return a.pst.value="",a.pst.focus(),!1;if(!cb_checkform()||a.sub.disabled)return!1;set_status(t23);cbx.autoScroll(!0);a.pst.value="";a.pst.focus();for(var c={aj:cbx.ver,lp:cbx.lp,pst:b},d="nme eml key ekey fkey pic auth captme capword caphash".split(" "),e=0;e<d.length;e++){var g=d[e];!a[g]||""===a[g].value||"eml"==g&&a[g].value==t5||(c[g]=a[g].value)}cbx.xhr("index.php?"+s_rq+"&sec=submit",
c,function(c,d){c=c||"";var e=c.split("\n")[0].split("\t");if(!c||e[0]||d){if(a.pst.value==t3||""==a.pst.value)a.pst.value=b;set_status(t12+" "+(e[0]||d))}else set_status(""),a.pst.focus(),cbx.user.nme=a.nme.value,cbx.user.eml=a.eml?a.eml.value:null;cbx.aj_proc(c)})||(a.pst.value=b);return!1};
cbx.aj_proc=function(a){var b=a.split("\n"),c=b[0].split("\t");if(!a)return!1;for(a=b.length-1;0<a;a--)cbx.parseMsg(b[a]);0<1*c[1]&&cbx.aonliners(c[1]);c[3]&&cbx.updateKey(c[3]);cbx.prefs.timeDelta=Math.round(1*c[2]-(new Date).getTime()/1E3);c[5]&&(cbx.user.lpid=1*c[5]);b.length-1&&(cbx.upd_tms(),cbx.delban());return b.length-1};
cbx.updateKey=function(a){if(a&&(f.key.value=a,cbx.user.key!==a)){var b=cbx.user.lvl;cbx.user.lvl=0;cbx.user.key=a;s_uo?s_uo&&(3==s_uo?cbx.getlvlhint():cbx.user.lvl=1):cbx.user.lvl=1*a.substring(a.length-1,a.length);cbx.user.lvl!==b&&cbx.delban()}};window.ar_reset=function(){cbx.debug.log("ar_reset called");s_ar&&(cbx.arMgr.state||cbx.arMgr.run())};
cbx.arMgr={state:0,backoff:2E3,run:function(){cbx.arMgr.state=0;var a=function(){cbx.arMgr.backoff=Math.min(36E4,Math.floor(cbx.arMgr.backoff*(1.5+Math.random())))},b=function(){cbx.arMgr.backoff=Math.floor(1E3*(1.5+Math.random()))};cbx.lpStart();cbx.arMgr.state=0;var c=function(){cbx.flconn.onstatechange=null;cbx.arMgr.state=1;cbx.debug.log("ARMGR: Attempting WS");cbx.lpStart();a();cbx.wsconn.onstatechange=function(){4===cbx.wsconn.state&&(cbx.debug.log("ARMGR: WS connected"),cbx.arMgr.state=3,cbx.lpStop(),
b(),window.clearTimeout(e),cbx.wsconn.onstatechange=function(){0==cbx.wsconn.state&&(cbx.debug.log("ARMGR: WS disconnected. Retrying in "+cbx.arMgr.backoff),cbx.lpStart(),cbx.arMgr.state=0,window.setTimeout(c,cbx.arMgr.backoff))})};wsStart(window.wsuri);var e=window.setTimeout(d,1E4+cbx.arMgr.backoff)},d=function(){cbx.wsconn.onstatechange=null;cbx.debug.log("ARMGR: Attempting FL");cbx.arMgr.state=2;cbx.lpStart();a();cbx.flconn.onstatechange=function(){4===cbx.flconn.state&&(cbx.debug.log("ARMGR: FL connected"),
cbx.arMgr.state=4,cbx.lpStop(),b(),window.clearTimeout(e),cbx.flconn.onstatechange=function(){0==cbx.flconn.state&&(cbx.debug.log("ARMGR: FL disconnected"),cbx.lpStart(),cbx.arMgr.state=0,window.setTimeout(d,cbx.arMgr.backoff))})};startFlashRelay();var e=window.setTimeout(c,1E4+cbx.arMgr.backoff)};window.setTimeout(c,2E3);window.setTimeout(function(){s_on&&(cbx.debug.log("ARMGR: Sending first ping"),cbx.xhr("./?"+s_rq+"&sec=ar&p="+cbx.lp+"&c="+cbx.unixTime(),null,function(a,b){}),window.setInterval(function(){cbx.debug.log("ARMGR: Sending ping");
cbx.xhr("./?"+s_rq+"&sec=ar&p="+cbx.lp+"&c="+cbx.unixTime(),null,function(a,b){})},6E4))},1E3)}};cbx.lpconn={enabled:!0,state:0,tmeLastRequest:0,curWait:0,lastErr:null,numMessages:0,numRequests:0};cbx.lpStop=function(){cbx.lpconn.enabled=!1};cbx.lpStart=function(){var a=cbx.lpconn.enabled&&cbx.lpconn.state;cbx.lpconn.enabled=!0;a||cbx.lpLoop()};
cbx.lpLoop=function(){var a=cbx.lp;if(0<cbx.lpconn.state)return!1;cbx.lpconn.state=1;cbx.lpconn.numRequests++;cbx.lpconn.tmeLastRequest=(new Date).getTime();cbx.xhr("../sub2?id="+s_id+"_"+s_tid+"&ev="+a,null,function(a,c){cbx.lpconn.lastErr=c;var d=(new Date).getTime()-cbx.lpconn.tmeLastRequest;cbx.lpconn.curWait=Math.max(2E3,8E3-d)+Math.floor(5E3*Math.random());window.setTimeout(function(){cbx.lpconn.state=0;cbx.lpconn.enabled&&cbx.lpLoop()},cbx.lpconn.curWait);if(a&&!c)for(var d=(a||"").split("\n"),
e=0;e<d.length;e++)cbx.rpcProcess(d[e]),cbx.lpconn.numMessages++},18E4);return!0};
cbx.flash={obj:null,readyState:0,load:function(){window.fl_ready=function(){cbx.flash.readyState=2;cbx.flash.onready()};window.fl_gotconn=function(){cbx.flash.onopen()};window.fl_pclosed=function(){cbx.flash.onclose()};window.fl_gotmsg=function(a){cbx.flash.onmessage(a)};cbx.flash.obj=loadSWF("ARswf",window.fluri);cbx.flash.readyState=1},open:function(){cbx.flash.obj&&1<cbx.flash.readyState?cbx.flash.obj.doConn():cbx.debug.log("Open called on not-ready Flash!")},close:function(){cbx.flash.obj&&1<
cbx.flash.readyState?cbx.flash.obj.endConn():cbx.debug.log("Close called on not-ready Flash!")},onready:function(){},onmessage:function(a){},onopen:function(){},onclose:function(){}};
var flconn={id:null,hash:null,pool:null,state:0,numAttempts:0,numCommands:0,numMessages:0,onstatechange:null},startFlashRelay=function(){var a=null,b=function(a){if(a!=flconn.state&&(flconn.state=a,flconn.onstatechange))flconn.onstatechange()},c=function(b,c){null!=a&&(window.clearTimeout(a),a=null);b&&(a=window.setTimeout(function(){cbx.debug.log("FLAR: timer fired");b()},c))},d=function(){cbx.debug.log("FLAR: failed");flconn.pool=null;flconn.id=null;flconn.hash=null;b(0);c(null)};cbx.flash.onclose=
function(){cbx.debug.log("FLAR: closed");b(0);d()};var e=function(){flconn.curAttempts++;cbx.debug.log("FLAR: opening");c(d,1E4);cbx.flash.open();b(1)};cbx.flash.onopen=function(){b(2);c(d,1E4)};cbx.flash.onmessage=function(a){flconn.numMessages++;4===flconn.state&&c(d,18E4);cbx.rpcProcess(a,function(a,e){flconn.numCommands++;"pool"==a&&(cbx.debug.log("FLAR: registered"),flconn.pool=e,c(d,18E4),b(4));"hash"==a&&(flconn.hash=e);"id"==a&&(flconn.id=e);flconn.id&&flconn.hash&&2==flconn.state&&(c(d,1E4),
b(3),cbx.debug.log("FLAR: registering"),(new Image).src="relayest.php?"+s_rq+"&cid="+flconn.id+"&chash="+flconn.hash+"&m=fl&t="+(new Date).getTime())})};0===cbx.flash.readyState?(cbx.debug.log("FLAR: loading"),cbx.flash.onready=function(){cbx.debug.log("FLAR: loaded");e()},cbx.flash.load()):e()};cbx.flconn=flconn;
var wsconn={id:null,hash:null,pool:null,state:0,tmeAttempted:0,tmeOpened:0,tmeHalfEst:0,tmeCompleted:0,numAttempts:0,curAttempts:0,curBackoff:0,numCommands:0,numMessages:0,log:[],onstatechange:null,socket:null};cbx.wsconn=wsconn;
var config={backoff:4,maxAttempts:5,connectTimeout:10,backoffScale:2,backoffResetDelay:15},wsStart=function(a){var b=function(a){if(a!=wsconn.state&&(wsconn.state=a,wsconn.onstatechange))wsconn.onstatechange()};try{wsconn.tmeAttempted=(new Date).getTime();wsconn.numAttempts++;wsconn.curAttempts++;cbx.debug.log("OPENING "+a);var c=null,d=function(a){var b={"\\\\":"\\","&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"',"&#039;":"'"};return a.replace(/(\\\\)|(&amp;)|(&lt;)|(&gt;)|(&quot;)|(&#039;)/g,function(a){return b[a]})};
b(1);var e=wsconn.socket=new WebSocket(a),g=window.setTimeout(function(){cbx.debug.log("TIMEOUT");e.close()},1E3*config.connectTimeout);e.onopen=function(){b(2);cbx.debug.log("OPEN");null!==g&&(window.clearTimeout(g),g=null);wsconn.tmeOpened=(new Date).getTime();wsconn.curAttempts=0;c=window.setTimeout(function(){wsconn.curBackoff=0},1E3*config.backoffResetDelay)};e.onclose=function(a){cbx.debug.log("CLOSE "+(a.wasClean?"CLEAN":"UNEXPECTED")+" ("+a.code+") "+a.reason);b(0);wsconn.id=null;wsconn.hash=
null;wsconn.pool=null;null!==g&&(window.clearTimeout(g),g=null);null!==c&&(window.clearTimeout(c),c=null)};e.onerror=function(a){cbx.debug.log("ERROR")};e.onmessage=function(a){wsconn.numMessages++;a=d(a.data);cbx.rpcProcess(a,function(a,c){wsconn.numCommands++;wsconn[a]=c;"pool"==a&&(cbx.debug.log("APP: Connected"),b(4),wsconn.tmeCompleted=(new Date).getTime());null!==wsconn.id&&null!==wsconn.hash&&2===wsconn.state&&(cbx.debug.log("APP: Registering"),b(3),wsconn.tmeHalfEst=(new Date).getTime(),(new Image).src=
"relayest.php?"+s_rq+"&cid="+wsconn.id+"&chash="+wsconn.hash+"&m=ws&t="+(new Date).getTime())})}}catch(h){return b(0),cbx.debug.log("Caught exception: "+h.message+" "+h.stack),!1}};window.togglear=function(a){};cbx.aonliners=function(a){a*=1;var b=document.getElementById("onliners");a&&b&&(b.innerHTML=a+"&nbsp;"+(1==a?t7:t8))};var scrollFollow=!0,scrollHeightPrev=null;
cbx.autoScroll=function(a){var b=cbm.document.getElementById("bdy");b&&!cbx.disableAutoScroll&&(a&&(scrollFollow=!0),b=cbm.document.documentElement||b,scrollFollow?s_sd?cbm.scrollTo(0,b.scrollHeight):cbm.scrollTo(0,0):!s_sd&&scrollHeightPrev&&cbm.scrollBy&&cbm.scrollBy(0,b.scrollHeight-scrollHeightPrev),scrollHeightPrev=b.scrollHeight)};
cbx.onScroll=function(){var a=cbm.document.getElementById("bdy"),b=Infinity,c=0;cbm.document.documentElement&&(b=cbm.document.documentElement.clientHeight,c=cbm.document.documentElement.scrollTop);b=Math.min(b,a.clientHeight);c=Math.max(c,a.scrollTop);scrollFollow=s_sd&&c+b>a.scrollHeight-10?!0:!s_sd&&10>c?!0:!1};
cbx.rsz=function(a){cbx.debug.log("RSZ called");var b=document.documentElement&&document.documentElement.clientWidth||document.body.clientWidth,c=document.documentElement&&document.documentElement.clientHeight||document.body.clientHeight;a=cbx.$frm;a.nme&&(a.nme.style.boxSizing="border-box",a.nme.style.MozBoxSizing="border-box",a.nme.style.webkitBoxSizing="border-box");a.eml&&(a.eml.style.boxSizing="border-box",a.eml.style.MozBoxSizing="border-box",a.eml.style.webkitBoxSizing="border-box");a.pst&&
(a.pst.style.boxSizing="border-box",a.pst.style.MozBoxSizing="border-box",a.pst.style.webkitBoxSizing="border-box");!s_ae||s_uo||s_fa?(s_uo||(a.nme.style.width=b-8+"px"),s_ae&&!s_uo&&(a.eml.style.width=b-8+"px")):(a.nme.style.width=Math.max(Math.ceil(b/2-6),1)+"px",a.eml.style.width=Math.max(Math.floor(b/2-6),1)+"px");a.pst.style.width=s_fa?b-8+"px":b-8-4-a.sub.offsetWidth+"px";1<s_fl?(b=c-(document.getElementsByTagName("table")[0].clientHeight-a.pst.clientHeight),a.pst.style.height=b-4+"px",s_fa||
(a.sub.style.height=b-4+"px")):(a.sub.style.height=a.pst.offsetHeight+"px",document.getElementById("tblmid").vAlign="center")};window.cb_checkform=function(){var a=cbx.$frm;return a.pst.value==t3?(set_status(t4),a.pst.focus(),!1):s_uo?!0:a.nme.value==t1?(set_status(t2),a.nme.focus(),!1):a.eml&&""!=a.eml.value&&a.eml.value!=t5&&0>=a.eml.value.lastIndexOf(".")&&0>=a.eml.value.lastIndexOf("@")?(set_status(t6),a.eml.focus(),!1):!0};function frmfocus(a,b){a.value==b&&(a.value="")}
function frmblur(a,b){""==a.value&&(a.value=b)}window.pop=function(a,b,c,d){var e=window.open("./?"+s_rq+"&sec="+a,"cb"+s_id+a.substring(0,3),"width="+b+", height="+c+", toolbar=no, scrollbars="+d+", status=no, resizable=yes");try{window.setTimeout(function(){var a=screen.height;e.moveTo(screen.width/2-b/2-100,a/2-a/4);e.focus()},10)}catch(g){}};window.crtn=function(a){var b=cbx.$frm;return 13==(window.event&&window.event.keyCode||a.keyCode||a.which)?(do_post()&&b.submit(),!1):!0};
function p_open(){var a=cbx.$frm;""==a.nme.value||a.nme.value==t1?(a.nme.focus(),alert(t2)):pop("profile&n="+esc(a.nme.value)+"&k="+a.key.value,480,320,0)}
function esc(a){return encodeURIComponent?encodeURIComponent(a):function(a){function c(a){function b(a,c){a+=c;return"%"+(16>a?"0":"")+a.toString(16).toUpperCase()}var c;c=127>=a?1:2047>=a?2:3;for(var d="",e=1;e<c;e++)d=b(a&63,128)+d,a>>>=6;return d=b(a,[0,192,224][c-1])+d}for(var d="",e=0;e<a.length;e++){var g=a.charCodeAt(e);if(128>g)var h=String.fromCharCode(g),d=-1!="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.!~*'()".indexOf(h)?d+h:d+c(g);else d+=c(g)}return d}(a)}
cbx.unixTime=function(){var a=cbx.prefs.timeDelta||0;return Math.round((new Date).getTime()/1E3)+a};
cbx.xhr=function(a,b,c,d){var e=null,g=null;d=d||2E4;if(window.XMLHttpRequest)e=new XMLHttpRequest;else if(window.ActiveXObject)try{e=new ActiveXObject("Msxml2.XMLHTTP")}catch(h){try{e=new ActiveXObject("Microsoft.XMLHTTP")}catch(k){}}if(!e)return!1;var l="-";e.onreadystatechange=function(){if(4==e.readyState){l=e.status;window.clearTimeout(g);var a=" ("+e.readyState+":"+l+")";if(0==e.status)return m(t14+"L-network"+a);if(200!=e.status)return m(t14+"R-server"+a);var b=e.responseText,d=b.substring(0,
1),b=b.substring(1);if("1"!=d&&"0"!=d)return m(t14+"R-chksum"+a);if("0"==d)return m("R-"+b);c(b,null)}};e.onerror=function(){m("L-connection")};var m=function(a){a=a||"L-timeout";window.clearTimeout(g);null!==e&&(e.onreadystatechange=function(){},e.abort(),e=null);c(null,a)},g=window.setTimeout(m,d);e.open(b?"POST":"GET",a,!0);e.setRequestHeader("Accept","*/*");e.responseType="text";if(b){e.setRequestHeader("Content-Type","application/x-www-form-urlencoded");a=[];for(var n in b)a.push(n+"="+esc(b[n]));
e.send(a.join("&"))}else e.send();return!0};function set_status(a,b){var c=[];c[0]=b?-1:0;c[1]=0;c[2]="";c[3]="";c[4]=0;c[5]="";c[6]=a;add_post(c)}var op;cbx.parseMsg=function(a){a=a.split("\t");0<a[0]&&1*a[0]>cbx.lp&&(cbx.lp=1*a[0]);add_post(a)&&(cbx.notifyParent("newMessage",null),cbx.newMessageAsync())};cbx.newMessageTmr=null;cbx.newMessageAsync=function(){cbx.newMessageTmr||(s_sn&&cbx.audio.play(cbx.prefs.sndVol),cbx.newMessageTmr=window.setTimeout(function(){cbx.newMessageTmr=null},1E3))};
var add_peer_post=function(a){var b=[-2];b[1]=cbx.unixTime();b[2]="-";b[3]="[Server]";b[4]=0;b[5]="";b[6]=a;b[8]=32;add_post(b);cbx.upd_tms()};window.op=0;
function add_post(a){if(cbm&&tbl&&cbm.document&&cbm.document.body){if(!a[6]||0<a[0]&&cbm.document.getElementById(a[0]))return!1;var b=tbl.rows.length,c=!1,d=!1;0<b&&(0==tbl.rows[0].id&&(tbl.deleteRow(0),b--),1<b&&0==tbl.rows[b-1].id&&(tbl.deleteRow(b-1),b--),1<b&&0==tbl.rows[1].id&&(tbl.deleteRow(1),b--),1<b&&0==tbl.rows[b-2].id&&(tbl.deleteRow(b-2),b--));if(0<b){(1==b&&!s_sd||1<b)&&-1==tbl.rows[0].id&&(c=!0);(1==b&&s_sd||1<b)&&-1==tbl.rows[b-1].id&&(d=!0);var e=tbl.rows[b-1].cells[0],g=tbl.rows[0].cells[0],
h=0<b-(d?1:0)-(c?1:0)?tbl.rows[b-1-(d?1:0)].cells[0]:null,k=0<b-(d?1:0)-(c?1:0)?tbl.rows[c?1:0].cells[0]:null;if(s_sd)l=tbl.insertRow(b-(d?1:0)),b++,b-(d?1:0)-(c?1:0)>s_mp&&0!=a[0]&&-1!=a[0]&&(c&&(g.className="stxt"==g.className?"stxt2":"stxt"),tbl.deleteRow(0+(c?1:0))),e=null!=h?"stxt"==h.className?"2":"":"2",op=tbl.rows[c?1:0].id;else{var l=tbl.insertRow(c?1:0);b++;b-(d?1:0)-(c?1:0)>s_mp&&0!=a[0]&&-1!=a[0]&&(d&&(e.className="stxt"==e.className?"stxt2":"stxt"),tbl.deleteRow(b-1-(d?1:0)),b--);e=null!=
k?"stxt"==k.className?"2":"":"2";op=tbl.rows[b-1-(d?1:0)].id}}else l=tbl.insertRow(0),e="2";l.id=a[0];b=l.insertCell(-1);b.className="stxt"+e+(a[8]&32?" oobpm":"");c="";if(0==a[0]||-1==a[0])c+='<div align="center">'+a[6]+"</div>";else{d=a[5].substring(a[5].length-4);s_av&&a[7]?c+='<img src="http://'+a[7]+'" class="pic">':!s_av||".gif"!=d&&".jpg"!=d&&".png"!=d||(c+='<img src="'+a[5]+'" class="pic">',a[5]="");1<s_dt&&(c+='<div class="dtxt'+e+'" id="t'+a[1]+'" '+(s_rt?'dir="ltr"':"")+">"+a[2]+"</div>");
a[8]&32&&(c+='<div class="dtxt'+e+'">('+t15+")</div>");0==s_al?a[5]&&(c+='<a href="'+a[5]+'" target="_blank">'):a[5]&&(c+='<a href="'+a[5]+'" target="_blank"><img src="extlink.gif" width="9" height="9" border="0" title="'+a[5]+'" style="vertical-align:middle; margin-right: 2px;"></a>');c+="<b";1==s_dt&&(c+=' title="'+a[2]+'"');d="nme ";switch(a[4]){case "1":d+="pn_std";break;case "2":d+="pn_reg";break;case "3":d+="pn_mod";break;case "4":d+="pn_adm"}c+=' class="'+d+'"';s_rt&&(c+=' dir="ltr"');c=c+
">"+a[3];c+="</b>";0==s_al&&a[5]&&(c+="</a>");c+=": "+a[6]}b.innerHTML=c;cbx.autoScroll();cbm.document.getElementById("jsdiv")&&(a=cbm.document.getElementById("jsdiv"),b=a.innerHTML,b=b.replace(/&amp;/g,"&"),eval(b),a.parentNode.removeChild(a));return!0}}var updTmsInt=null;
cbx.upd_tms=function(){if(3!=s_dt)return!0;for(var a=cbx.unixTime(),b=t16,c=cbm.document.getElementsByTagName("div"),d=[2592E3,604800,86400,3600,60,1],e=0;e<c.length;e++)if("dtxt"==c[e].className.substring(0,4)&&"t"==c[e].id.substring(0,1)){var g=a-1*c[e].id.substring(1);0>g&&(g=0);60>g&&(g=5*Math.ceil(g/5));for(var h=0;6>h;h++){var k=0;if(1<g/d[h]){g/=d[h];k=10-2*h;break}}c[e].title||(c[e].title=c[e].innerHTML);g=Math.round(g);c[e].innerHTML=t24.replace("%d",g).replace("%s",b[1==g?k:k+1])}null===
updTmsInt&&(updTmsInt=window.setInterval(cbx.upd_tms,5E3))};var lnkd=[];
cbx.delban=function(){var a=!1;cbx.updateKey(cbx.$frm.key.value);if(tbl){2<cbx.user.lvl&&(a=!0);for(var b=tbl.rows.length,c=0;c<b;c++){var d=tbl.rows[c];if(!(1>d.id)){var e=d.cells[0];lnkd[d.id]||(lnkd[d.id]=!0,e.innerHTML=e.innerHTML.replace(/(div>|pic\">|^)<(a|b)/i,'$1<span class="modtools" id="mod_'+d.id+'"></span><$2'));var g=cbm.document.getElementById("mod_"+d.id);g&&(g.innerHTML="",(a||s_ld&&d.id==cbx.user.lpid==cbx.lp&&1<cbx.user.lvl)&&function(b){var c=document.createDocumentFragment(),d=
document.createElement("a");d.title=t17;d.href="javascript:void(0)";d.innerHTML="[&times;]&nbsp;";d.onclick=function(){cbx.del(b);return!1};c.appendChild(d);if(a){var e=document.createElement("a");e.title=t18;e.href="javascript:void(0)";e.innerHTML="[o]&nbsp;";e.onclick=function(){cbx.ban(b);return!1};e.onmouseover=function(){cbx.getip(b,e)};c.appendChild(e)}g.appendChild(c)}(d.id))}}if(0!=s_al&&document.getElementsByTagName)for(b=cbm.document.getElementsByTagName("b"),c=0;c<b.length;c++)-1!=b[c].className.indexOf("nme")&&
(b[c].onmousedown=function(a){a||(a=cbm.event);a.cancelBubble=!0;a.returnValue=!1;a.stopPropagation&&a.stopPropagation();a.preventDefault&&a.preventDefault();return!1},b[c].onclick=function(a){a||(a=cbm.event);a.shiftKey&&0<s_pm?popout(this.innerHTML):quote_text("@"+this.innerHTML,"","","")},b[c].style.cursor="pointer")}};cbx.getlvlhint=function(){var a=cbx.$frm;cbx.xhr("./?"+s_rq+"&sec=getlvl&n="+esc(a.nme.value)+"&k="+a.key.value,null,function(a,c){if(!a)return!1;cbx.user.lvl=1*a;cbx.delban()})};
cbx.ban=function(a){var b=cbx.$frm,c=prompt(t21,"7 days");null!=c&&cbx.xhr("./?"+s_rq+"&sec=delban&n="+esc(b.nme.value)+"&k="+b.key.value+"&ban="+a+"&dur="+esc(c),null,function(a,b){b&&set_status(b);if(!a)return!1;a=a.split("\t");alert(a[1])})};cbx.del=function(a){var b=cbx.$frm;cbx.xhr("./?"+s_rq+"&sec=delban&n="+esc(b.nme.value)+"&k="+b.key.value+"&del="+a,null,function(a,b){b&&set_status(b);if(!a)return!1;cbx.del_proc(a)})};
cbx.del_proc=function(a,b){b=b||a;for(var c=tbl.rows.length,d=0;d<c&&tbl.rows[d];d++)1*tbl.rows[d].id>=1*a&&1*tbl.rows[d].id<=1*b&&(tbl.rows[d].cells[0].innerHTML='<div align="center"><i>'+t22+"</i></div>",tbl.rows[d]._deleted=!0)};
cbx.proc_rpc_del=function(a){a=a.split(",");for(var b,c,d=0;d<a.length;d++)if(0>a[d].indexOf("_"))b=parseInt(a[d]),isNaN(b)||cbx.del_proc(b);else if(c=a[d].split("_"),b=parseInt(c[0]),c=parseInt(c[1]),!isNaN(b)&&!isNaN(c)&&100>c-b){var e=Math.min(0<1*tbl.rows[0].id?1*tbl.rows[0].id:0,0<1*tbl.rows[tbl.rows.length-1].id?1*tbl.rows[tbl.rows.length-1].id:0),g=Math.max(0<1*tbl.rows[0].id?1*tbl.rows[0].id:0,0<1*tbl.rows[tbl.rows.length-1].id?1*tbl.rows[tbl.rows.length-1].id:0);b=Math.max(b,e);c=Math.min(c,
g);if(c-b>=s_mp)cbx.del_proc(b,c);else for(;b<=c;b++)cbx.del_proc(b)}};var gips=[];cbx.getip=function(a,b){var c=cbx.$frm;gips[a]||(cbx.xhr("./?"+s_rq+"&sec=getip&n="+esc(c.nme.value)+"&k="+c.key.value+"&i="+a+"&r="+(new Date).getTime(),null,function(c,e){if(!c||e)return gips[a]=!1;b&&(b.title=t18+" (IP: "+c+")")}),gips[a]=!0)};window.togglesnd=function(){var a=cbx.prefs.sndVol;switch(a){case 0:a=100;break;case 20:a=0;break;default:a=20}cbx.setSndVol(a);cbx.audio.play(a)};
cbx.setSndVol=function(a){var b=0,c=document.getElementById("sndctrl");switch(a){case 20:b=16;break;case 100:b=32}c.style.left=-1*b+"px";cbx.prefs.sndVol=a};var titleT=null;function titleflash(){if(0!=s_pp){var a=!1,b=0;parent.document.title="New message! - Cbox";titleT&&window.clearInterval(titleT);titleT=window.setInterval(function(){parent.document.title=a&&0==foc?"New message! - Cbox":"Cbox";a=a?!1:!0;(13<b++||0!=foc)&&window.clearInterval(titleT)},2E3)}}
var loadSWF=function(a,b){function c(a,b){return'<param name="'+a+'" value="'+b+'">'}window.document.getElementsByTagName("html");var d,e;d={name:a,id:a,src:b,quality:"high",allowScriptAccess:"always",bgcolor:"#ffffff",pluginspage:"http://www.macromedia.com/go/getflashplayer",title:"Flash magic",type:"application/x-shockwave-flash",hasPriority:"true"};e={position:"absolute",width:"8px",height:"8px",bottom:"0px",left:"-10px",overflow:"hidden","z-index":"10000"};var g="",h;for(h in d)g+=h+'="'+d[h]+
'" ';var k="";for(h in e)k+=h+": "+e[h]+"; ";d=['<object style="'+k+'" id="'+a+'" data="'+b+'" type="'+d.type+'" title="'+d.title+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0">',c("movie",b),c("AllowScriptAccess",d.allowScriptAccess),c("quality",d.quality),c("bgcolor",d.bgcolor),c("hasPriority",d.hasPriority),"<embed "+g+">","</object>"].join("");e=document.getElementById("flash_"+a)||document.createElement("div");
e.id="flash_"+a;document.body.appendChild(e);e.innerHTML=d;return document[a]};
cbx.audio=function(){var a=function(a){cbx.debug.log("AUDIO "+a)};return{play:function(){a("Play called but not configured.")},setup:function(b){a("Setup called with "+b);var c=null,d=function(){window.soundManager={_externalInterfaceOK:function(d){a("SWF: ExternalInterface online! Version: "+d);window.setTimeout(function(){c._createSound("cbxsnd",1,!1)},100);window.setTimeout(function(){a("Flash: loading "+b+".mp3");c._load("cbxsnd",b+".mp3",!0,!1,!1)},500)},sounds:{cbxsnd:{_onload:function(b){b?
(a("SWF: Loaded - configuring for play."),cbx.audio.play=function(b){a("Flash play called at volume "+b);c._setVolume("cbxsnd",b);c._start("cbxsnd",1,0,!1)}):a("SWF: Load failed - not switching play")},_onfinish:function(){a("SWF: Got onfinish")}}}};cbx.audio.play=function(b){a("Play waiting on flash")};a("Attempting to load Flash object...");var c=loadSWF("SMswf",window.smuri)};if(!("Audio"in window))return a("No Audio object found - fast fallback."),d(),!1;var e=null,c=new Audio,g=function(){window.clearTimeout(k);
c?(a("Ready: Canplaythrough duration "+c.duration+". Setting play() handler"),cbx.audio.play=function(b){e?a("Play ongoing."):(a("Play called at volume "+b),e=window.setTimeout(function(){a("Play timeout. Falling back.");d()},3E3),cbx.audio.playStart=(new Date).getTime(),c.volume=b/100,c.play())},c.removeEventListener("canplaythrough",g,!1)):a("Ready fired but object destroyed.")},h=".ogg";c.canPlayType&&c.canPlayType('audio/ogg; codecs="vorbis"').replace(/no/,"")||(h=".mp3");a("Audio object created; chose "+
h);var k=window.setTimeout(function(){a("Load timeout. Falling back.");c=null;d()},5E3);c.addEventListener("canplaythrough",g,!1);c.addEventListener("error",function(b){a("Got error. Falling back");window.clearTimeout(k);e&&window.clearTimeout(e);c=null;d()},!1);c.addEventListener("timeupdate",function(b){c.currentTime&&null!==e&&(a("Play underway!"),window.clearTimeout(e),e=null)},!1);a("Setting source: "+b+h);c.setAttribute("src",b+h)}}}();window.delban=cbx.delban;window.aonliners=cbx.aonliners;
